# Generated by Django 5.1.6 on 2025-02-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый рабочий стол', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktops', to='custom_auth.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DesktopAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='fileManager.desktop')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_desktops', to='custom_auth.teachermodel')),
            ],
            options={
                'unique_together': {('desktop', 'teacher')},
            },
        ),
    ]
