# Generated by Django 5.1.6 on 2025-02-11 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_iin', message='IIN must be exactly 12 digits.', regex='^\\d{12}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Не замужем/Не женат'), ('married', 'Замужем/Женат'), ('divorced', 'Разведен/Разведена')], max_length=20, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document_issue_date', models.DateField(blank=True, null=True)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_address', models.TextField(blank=True, null=True)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('teaching_language', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(code='invalid_iin', message='IIN must be exactly 12 digits.', regex='^\\d{12}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=30, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=30, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('was_born_in_another_country', models.BooleanField(default=False)),
                ('locality_of_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_address', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_residence', models.CharField(blank=True, max_length=50, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.groupmodel')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TeacherForeignLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('A1', 'A1 - Начальный'), ('A2', 'A2 - Элементарный'), ('B1', 'B1 - Средний'), ('B2', 'B2 - Выше среднего'), ('C1', 'C1 - Продвинутый'), ('C2', 'C2 - Владение')], max_length=2)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_languages', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_foreign_language',
            },
        ),
        migrations.CreateModel(
            name='TeacherEducationRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('document_details', models.TextField()),
                ('graduation_year', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('foreign_institution', models.BooleanField(default=False)),
                ('scan_copy', models.FileField(blank=True, null=True, upload_to='education_scans/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_education_record',
            },
        ),
        migrations.CreateModel(
            name='TeacherCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('confirmation_document', models.FileField(blank=True, null=True, upload_to='confirmation_documents/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_category',
            },
        ),
        migrations.CreateModel(
            name='TeacherAuthTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_auth_token',
            },
        ),
        migrations.CreateModel(
            name='TeacherAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_auth',
            },
        ),
        migrations.CreateModel(
            name='TeacherAchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_achievement',
            },
        ),
        migrations.CreateModel(
            name='TeacherScienceFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('academic_degree', models.CharField(max_length=100)),
                ('academic_status', models.CharField(max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science_fields', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_science_field',
            },
        ),
    ]
