# Generated by Django 5.1.6 on 2025-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_enrollment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
