# Generated by Django 5.1.7 on 2025-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='form_of_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
