# Generated by Django 5.1.7 on 2025-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_studentmodel_form_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Не замужем/Не женат'), ('married', 'Замужем/Женат'), ('divorced', 'Разведен/Разведена')], max_length=30, null=True),
        ),
    ]
