# Generated by Django 5.1.7 on 2025-04-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_studentmodel_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teachers', to='custom_auth.groupmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to='custom_auth.teachermodel')),
            ],
            options={
                'db_table': 'teacher_group',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'group'), name='unique_teacher_group')],
            },
        ),
    ]
