# Generated by Django 5.1.7 on 2025-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_teachergroupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='document_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
